### ISSUE TITLE
laravel 5.6 无法正常运行

### ISSUE THREAD

**Issue by hooklife** [scil/LaravelFly#16]
使用默认配置 start后报错
```
[INFO] conf: /opt/www/laravel-test/fly.conf.php
[INFO] server dispatcher created
[INFO] event server.config
[INFO] include: /opt/www/laravel-test/bootstrap/cache/laravelfly_preload.php
[WARN] kernel: LaravelFly\Kernel
[INFO] event server.created for LaravelFly\Server\HttpServer
[INFO] event worker.starting for 0 (pid 24042)
[INFO] event worker.starting for 1 (pid 24043)
[INFO] event worker.starting for 2 (pid 24044)
[INFO] event worker.starting for 3 (pid 24045)
[INFO] event worker.starting for 4 (pid 24046)
[INFO] event app.created for \LaravelFly\Simple\Application (pid 24043)
[INFO] event app.created for \LaravelFly\Simple\Application (pid 24044)
[INFO] event app.created for \LaravelFly\Simple\Application (pid 24045)
[INFO] event app.created for \LaravelFly\Simple\Application (pid 24042)
[INFO] event app.created for \LaravelFly\Simple\Application (pid 24046)
[ERROR] bootstrap: Whoops\Exception\ErrorException: array_diff(): Argument #2 is not an array in /opt/www/laravel-test/vendor/scil/laravel-fly/src/LaravelFly/Simple/Bootstrap/LoadConfiguration.php:39
Stack trace:
#0 [internal function]: Whoops\Run->handleError(2, 'array_diff(): A...', '/opt/www/larave...', 39, Array)
#1 /opt/www/laravel-test/vendor/scil/laravel-fly/src/LaravelFly/Simple/Bootstrap/LoadConfiguration.php(39): array_diff(Array, NULL, NULL)
#2 /opt/www/laravel-test/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(206): LaravelFly\Simple\Bootstrap\LoadConfiguration->bootstrap(Object(LaravelFly\Simple\Application))
#3 /opt/www/laravel-test/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(162): Illuminate\Foundation\Application->bootstrapWith(Array)
#4 /opt/www/laravel-test/vendor/scil/laravel-fly/src/LaravelFly/Server/HttpServer.php(59): Illuminate\Foundation\Http\Kernel->bootstrap()
#5 {main}
[ERROR] bootstrap: Whoops\Exception\ErrorException: array_diff(): Argument #2 is not an array in /opt/www/laravel-test/vendor/scil/laravel-fly/src/LaravelFly/Simple/Bootstrap/LoadConfiguration.php:39
Stack trace:
#0 [internal function]: Whoops\Run->handleError(2, 'array_diff(): A...', '/opt/www/larave...', 39, Array)
#1 /opt/www/laravel-test/vendor/scil/laravel-fly/src/LaravelFly/Simple/Bootstrap/LoadConfiguration.php(39): array_diff(Array, NULL, NULL)
#2 /opt/www/laravel-test/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(206): LaravelFly\Simple\Bootstrap\LoadConfiguration->bootstrap(Object(LaravelFly\Simple\Application))
#3 /opt/www/laravel-test/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(162): Illuminate\Foundation\Application->bootstrapWith(Array)
#4 /opt/www/laravel-test/vendor/scil/laravel-fly/src/LaravelFly/Server/HttpServer.php(59): Illuminate\Foundation\Http\Kernel->bootstrap()
#5 {main}
[INFO] event worker.ready for id 1
[INFO] event worker.ready for id 2
[ERROR] bootstrap: Whoops\Exception\ErrorException: array_diff(): Argument #2 is not an array in /opt/www/laravel-test/vendor/scil/laravel-fly/src/LaravelFly/Simple/Bootstrap/LoadConfiguration.php:39
Stack trace:
#0 [internal function]: Whoops\Run->handleError(2, 'array_diff(): A...', '/opt/www/larave...', 39, Array)
#1 /opt/www/laravel-test/vendor/scil/laravel-fly/src/LaravelFly/Simple/Bootstrap/LoadConfiguration.php(39): array_diff(Array, NULL, NULL)
#2 /opt/www/laravel-test/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(206): LaravelFly\Simple\Bootstrap\LoadConfiguration->bootstrap(Object(LaravelFly\Simple\Application))
#3 /opt/www/laravel-test/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(162): Illuminate\Foundation\Application->bootstrapWith(Array)
#4 /opt/www/laravel-test/vendor/scil/laravel-fly/src/LaravelFly/Server/HttpServer.php(59): Illuminate\Foundation\Http\Kernel->bootstrap()
#5 {main}
[INFO] event worker.ready for id 3
[2018-05-22 15:34:04 #24034.5]  NOTICE  Server is shutdown now.
[INFO] event worker.stopped for id 2
[INFO] event worker.stopped for id 1
[INFO] event worker.stopped for id 3

```

**Comment by scil** [comment]
I don't think there's a file scil/laravel-fly/src/LaravelFly/Simple/Bootstrap/LoadConfiguration.php

could you try `composer update`?

**Comment by aftabnaveed** [comment]
I don't know why this issue is closed, no solution is proposed here. I am using 5.6 and can reproduce the above error. 

```
[INFO] conf: /srv/laraveltest/fly.conf.php
[INFO] server dispatcher created
[INFO] event server.config
[INFO] include pre-files
[WARN] kernel: LaravelFly\Kernel
[INFO] event server.created for LaravelFly\Server\HttpServer
[2018-06-04 06:07:20 @105.0]	TRACE	Create swoole_server host=0.0.0.0, port=8080, mode=3, type=1
[INFO] event worker.starting for 0 (pid 112)
[INFO] event worker.starting for 1 (pid 113)
[INFO] event worker.starting for 2 (pid 114)
[INFO] event app.created for \LaravelFly\Simple\Application (pid 112)
[INFO] event app.created for \LaravelFly\Simple\Application (pid 113)
[INFO] event worker.starting for 4 (pid 116)
[INFO] event worker.starting for 3 (pid 115)
[INFO] event app.created for \LaravelFly\Simple\Application (pid 114)
[INFO] event app.created for \LaravelFly\Simple\Application (pid 116)
[INFO] event app.created for \LaravelFly\Simple\Application (pid 115)
[ERROR] bootstrap: Whoops\Exception\ErrorException: array_diff(): Argument #2 is not an array in /srv/laraveltest/vendor/scil/laravel-fly/src/LaravelFly/Simple/Bootstrap/LoadConfiguration.php:39
Stack trace:
#0 [internal function]: Whoops\Run->handleError(2, 'array_diff(): A...', '/srv/laraveltes...', 39, Array)
#1 /srv/laraveltest/vendor/scil/laravel-fly/src/LaravelFly/Simple/Bootstrap/LoadConfiguration.php(39): array_diff(Array, NULL, NULL)
#2 /srv/laraveltest/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(206): LaravelFly\Simple\Bootstrap\LoadConfiguration->bootstrap(Object(LaravelFly\Simple\Application))
#3 /srv/laraveltest/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(162): Illuminate\Foundation\Application->bootstrapWith(Array)
#4 /srv/laraveltest/vendor/scil/laravel-fly/src/LaravelFly/Server/HttpServer.php(59): Illuminate\Foundation\Http\Kernel->bootstrap()
#5 {main}
[INFO] watch /srv/laraveltest/storage/framework/down.
[2018-06-04 06:07:20 #105.5]	NOTICE	Server is shutdown now.
[INFO] event worker.ready for id 0
[2018-06-04 06:07:20 $106.0]	TRACE	[Manager]kill worker processor
[2018-06-04 06:07:20 $106.0]	TRACE	[Manager]kill worker processor
[2018-06-04 06:07:20 $106.0]	TRACE	[Manager]kill worker processor
[2018-06-04 06:07:20 $106.0]	TRACE	[Manager]kill worker processor
[2018-06-04 06:07:20 $106.0]	TRACE	[Manager]kill worker processor
[INFO] event worker.stopped for id 0

```

**Comment by aftabnaveed** [comment]
I am able to fix the problem by copying 
`vendor/scil/laravel-fly/config/laravelfly-app-config.example.php`  to  `config/laravelfly.php`

I think this should be publishable via `php artisan publish` command

**Comment by scil** [comment]
Thank you.

I just added `php artisan vendor:publish --tag=fly-app` to readme.md
