### ISSUE TITLE
启动报错，#21 {main}[FLY ERROR] bootstrap: Class xxxx does not exist

### ISSUE THREAD

**Issue by zhenyangze** [scil/LaravelFly#28]
1. laravel5.6最基本的版本中，是没有问题的。
2. 迁移到项目上后，开始报错了。
3. 提示找不到files方法，修改后会提示找不到Auth方法。

### provider
```php
    'providers' => [

        /*
         * Laravel Framework Service Providers...
         */
        Illuminate\Auth\AuthServiceProvider::class,
        Illuminate\Broadcasting\BroadcastServiceProvider::class,
        Illuminate\Bus\BusServiceProvider::class,
        Illuminate\Cache\CacheServiceProvider::class,
        Illuminate\Foundation\Providers\ConsoleSupportServiceProvider::class,
        Illuminate\Cookie\CookieServiceProvider::class,
        Illuminate\Database\DatabaseServiceProvider::class,
        Illuminate\Encryption\EncryptionServiceProvider::class,
        Illuminate\Filesystem\FilesystemServiceProvider::class,
        Illuminate\Foundation\Providers\FoundationServiceProvider::class,
        Illuminate\Hashing\HashServiceProvider::class,
        Illuminate\Mail\MailServiceProvider::class,
        Illuminate\Notifications\NotificationServiceProvider::class,
        Illuminate\Pagination\PaginationServiceProvider::class,
        Illuminate\Pipeline\PipelineServiceProvider::class,
        Illuminate\Queue\QueueServiceProvider::class,
        Illuminate\Redis\RedisServiceProvider::class,
        Illuminate\Auth\Passwords\PasswordResetServiceProvider::class,
        Illuminate\Session\SessionServiceProvider::class,
        Illuminate\Translation\TranslationServiceProvider::class,
        Illuminate\Validation\ValidationServiceProvider::class,
        Illuminate\View\ViewServiceProvider::class,

        /*
         * Package Service Providers...
         */

        /*
         * Application Service Providers...
         */
        App\Providers\AppServiceProvider::class,
        App\Providers\AuthServiceProvider::class,
        // App\Providers\BroadcastServiceProvider::class,
        App\Providers\EventServiceProvider::class,
        App\Providers\RouteServiceProvider::class,
        Laravel\Passport\PassportServiceProvider::class,
        SimpleSoftwareIO\QrCode\QrCodeServiceProvider::class,

        Intervention\Image\ImageServiceProvider::class,
        \Yangyifan\Upload\UploadServiceProvider::class,
        \App\Providers\Cee\Volunteer\VolunteerProvider::class,
        App\Providers\Cee\Major\EvaluationProvider::class,
        App\Providers\Im\TimProvider::class,
        //Hhxsv5\LaravelS\Illuminate\LaravelSServiceProvider::class,
        Silber\PageCache\LaravelServiceProvider::class,
    ],
```

### 错误代码
```shell
#0 /www/htdocs/vendor/scil/laravel-fly-files/src/Container.php(701): ReflectionClass->__construct('files')
#1 /www/htdocs/vendor/scil/laravel-fly-files/src/Container.php(578): Illuminate\Container\Container->build('files')
#2 /www/htdocs/vendor/scil/laravel-fly-files/src/Container.php(533): Illuminate\Container\Container->resolve('files', -1, Array)
#3 /www/htdocs/vendor/scil/laravel-fly-files/src/Application.php(697): Illuminate\Container\Container->make('files', Array)
#4 /www/htdocs/vendor/scil/laravel-fly-files/src/Container.php(1154): Illuminate\Foundation\Application->make('files')
#5 /www/htdocs/vendor/barryvdh/laravel-ide-helper/src/IdeHelperServiceProvider.php(118): Illuminate\Container\Container->offsetGet('files')
#6 /www/htdocs/vendor/barryvdh/laravel-ide-he#0 /www/htdocs/vendor/scil/laravel-fly-files/src/Container.php(701): ReflectionClass->__construct('files')
#1 /www/htdocs/vendor/scil/laravel-fly-files/src/Container.php(578): Illuminate\Container\Container->build('files')
#2 /www/htdocs/vendor/scil/laravel-fly-files/src/Container.php(533): Illuminate\Container\Container->resolve('files', -1, Array)
#3 /www/htdocs/vendor/scil/laravel-fly-files/src/Application.php(697): Illuminate\Container\Container->make('files', Array)
#4 /www/htdocs/vendor/scil/laravel-fly-files/src/Container.php(1154): Illuminate\Foundation\Application->make('files')
#5 /www/htdocs/vendor/barryvdh/laravel-ide-helper/src/IdeHelperServiceProvider.php(118): Illuminate\Container\Container->offsetGet('files')
#6 /www/htdocs/vendor/barryvdh/laravel-ide-helper/src/IdeHelperServiceProvider.php(61): Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider->createLocalViewFactory()
#7 /www/htdocs/vendor/scil/laravel-fly-files/src/Application.php(546): Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider->register()
#8 /www/htdocs/app/Providers/AppServiceProvider.php(53): Illuminate\Foundation\Application->register(Object(Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider))
#9 /www/htdocs/vendor/scil/laravel-fly-files/src/Application.php(546): App\Providers\AppServiceProvider->register()
#10 /www/htdocs/vendor/scil/laravel-fly/src/LaravelFly/Backup/ProviderRepository.php(28): Illuminate\Foundation\Application->register(Object(App\Providers\AppServiceProvider))
#11 /www/htdocs/vendor/scil/laravel-fly/src/LaravelFly/Map/Application.php(242): LaravelFly\Backup\ProviderRepository->load(Array)
#12 /www/htdocs/vendor/scil/laravel-fly/src/LaravelFly/Map/Bootstrap/RegisterAcrossProviders.php(10): LaravelFly\Map\Application->registerAcrossProviders()
#13 /www/htdocs/vendor/scil/laravel-fly-files/src/Application.php(172): LaravelFly\Map\Bootstrap\RegisterAcrossProviders->bootstrap(Object(LaravelFly\Map\Application))
#14 /www/htdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(162): Illuminate\Foundation\Application->bootstrapWith(Array)
#15 /www/htdocs/vendor/scil/laravel-fly/src/LaravelFly/Server/Traits/Laravel.php(90): Illuminate\Foundation\Http\Kernel->bootstrap()
#16 /www/htdocs/vendor/scil/laravel-fly/src/LaravelFly/Server/HttpServer.php(32): LaravelFly\Server\Common->startLaravel()
#17 [internal function]: LaravelFly\Server\HttpServer->onWorkerStart(Object(Swoole\Http\Server), 3)
#18 /www/htdocs/vendor/scil/laravel-fly/src/LaravelFly/Server/Common.php(311): Swoole\Http\Server->start()
#19 /www/htdocs/vendor/scil/laravel-fly/src/LaravelFly/Server/HttpServer.php(23): LaravelFly\Server\Common->start()
#20 /www/htdocs/vendor/scil/laravel-fly/bin/fly(84): LaravelFly\Server\HttpServer->start()
#21 {main}[FLY ERROR] bootstrap: Class files does not exist
```

**Comment by scil** [comment]
do you have these two lines in config/laravelfly.php
```
    'providers_ignore' => array_merge([
           ...
                   'Barryvdh\\LaravelIdeHelper\\IdeHelperServiceProvider',
          ...
   

```

**Comment by zhenyangze** [comment]
yes, all ready added;
```php
    'providers_ignore' => array_merge([
        'Barryvdh\\LaravelIdeHelper\\IdeHelperServiceProvider',
        \Collective\Html\HtmlServiceProvider::class,
        \Laracasts\Flash\FlashServiceProvider::class,
        \Prettus\Repository\Providers\RepositoryServiceProvider::class,
        \InfyOm\Generator\InfyOmGeneratorServiceProvider::class,

    ], !!LARAVELFLY_SERVICES['broadcast'] ? [] : [
        Illuminate\Broadcasting\BroadcastServiceProvider::class,
        Illuminate\Broadcasting\BroadcastManager::class,
        Illuminate\Contracts\Broadcasting\Broadcaster::class,
        App\Providers\BroadcastServiceProvider::class
    ]

```

**Comment by scil** [comment]
why IdeHelperServiceProvider is ignored ,but stil booted?

**Comment by zhenyangze** [comment]
mybe i add IdeHelperServiceProvider in register
```php
    public function register()
    {
        //
        if (app()->environment() == 'local' || app()->environment() == 'testing') {
            $this->app->register(\Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider::class);
        }
    }
``` 

but after i move it to config/app.php,it show next error
```shell
#16 /www/htdocs//vendor/scil/laravel-fly/src/LaravelFly/Server/Traits/Laravel.php(90): Illuminate\Foundation\Http\Kernel->bootstrap()
#17 /www/htdocs//vendor/scil/laravel-fly/src/LaravelFly/Server/HttpServer.php(32): LaravelFly\Server\Common->startLaravel()
#18 [internal function]: LaravelFly\Server\HttpServer->onWorkerStart(Object(Swoole\Http\Server), 2)
#19 /www/htdocs//vendor/scil/laravel-fly/src/LaravelFly/Server/Common.php(311): Swoole\Http\Server->start()
#20 /www/htdocs//vendor/scil/laravel-fly/src/LaravelFly/Server/HttpServer.php(23): LaravelFly\Server\Common->start()
#21 /www/htdocs//vendor/scil/laravel-fly/bin/fly(84): LaravelFly\Server\HttpServer->start()
#22 {main}[FLY ERROR] bootstrap: Class auth does not exist
```

**Comment by zhenyangze** [comment]
已经解决了。
安装的Provider存在各种各样的问题。
已经发现的wechat, ossUpload, passport根据策略调整配置，基本就能解决问题了。

谢谢。

**Comment by fannyfan414** [comment]
> 已经解决了。
> 安装的Provider存在各种各样的问题。
> 已经发现的wechat, ossUpload, passport根据策略调整配置，基本就能解决问题了。
> 
> 谢谢。

How did you solve this problem? I have the same issue with Laravel passport "[LARAVEL BOOTSTRAP ERROR] Class auth does not exist"
